language: php

php:
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=3.2.*

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.3.* DEPS=dev
    - php: 5.6
      env: SYMFONY_VERSION=2.8.* COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - if [ "$DEPS" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update --prefer-dist $COMPOSER_FLAGS

script: phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
